# Generated by Django 5.2.5 on 2025-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createCV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='puesto',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
