# Generated by Django 5.2.5 on 2025-08-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createCV', '0002_experiencialaboral_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='institucion',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
